export const searchCatalog = [
  "Kurti",
  "Muslin Sharee",
  "Panjabi",
  "Salwar Kameez",
  "Hijab",
  "Lehenga",
  "Fatua",
  "Kaftan",
  "Saree Blouse",
  "T-Shirt",
  "Denim Jeans",
  "Lungi",
  "Polo Shirt",
  "Sneakers",
  "Handbag",
  "Kurti Tops",
  "Maxi Dress",
  "Shalwar Set",
  "Watch",
  "Sunglasses",
] as const;
