export const searchCatalog = [
  "Necklace",
  "Chain Necklace",
  "Cubic Necklace",
  "Pearl Necklace",
  "Layered Necklace",
  "Bracelet",
  "Gold Bangle",
  "Chain Bracelet",
  "Ring",
  "Statement Ring",
  "Zirconia Ring",
  "Earrings",
  "Teardrop Earrings",
  "Stud Earrings",
  "Pendant",
  "Sunburst Pendant",
  "Bangle",
  "Nakshi Bangle",
  "Nose Pin",
  "Pearl Nose Pin",
  "Kundan Nose Pin",
  "Jhumka",
  "Chandbali Jhumka",
  "Diamond",
  "Pearl",
  "Emerald",
  "21K Gold",
  "18K Gold",
] as const;